version: "3"
services:

    emby:
        image: emby/embyserver:latest
        restart: unless-stopped
        volumes:
            - /var/data/emby:/config
            - /mnt/media_1/movies:/data/movies
            - /mnt/media_1/home_movies:/data/home_movies
            - /mnt/media_1/photos:/data/photos:ro
            - "/mnt/media_2/Series:/data/tv"
            - "/mnt/media_1/cache/emby:/cache"
        devices:
            - /dev/dri/renderD128
        network_mode: "host"

   sonarr:
        image: linuxserver/sonarr
        restart: unless-stopped
        volumes:
            - "/var/data/sonarr/etc:/config"
            - "/mnt/media_2/Series:/tv"
            - /mnt/media_1/downloads:/downloads
        ports:
            - "8001:8989"
        # depends_on:
            # - vpn
        # links:
            # - vpn:nzb
        labels:
            - "traefik.frontend.rule=Host:tv.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."

    nzb:
        image: linuxserver/sabnzbd
        restart: unless-stopped
        volumes:
            - "/mnt/media_1/downloads:/downloads"
            - "/mnt/media_1/tmp_downloads:/incomplete-downloads"
            - "/var/data/nzb/etc:/config"
        ports:
            - "8002:8080"
        labels:
            - "traefik.frontend.rule=Host:nzb.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."

    potatoe:
        image: linuxserver/couchpotato
        restart: unless-stopped
        volumes:
            - "/var/data/couchpotatoe/etc:/config"
            - "/mnt/media_1/downloads:/downloads"
            - "/mnt/media_1/movies:/movies"
        ports:
            - "8003:5050"
        labels:
            - "traefik.frontend.rule=Host:movie.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."

    hydra:
        image: linuxserver/hydra2
        volumes:
            - /mnt/media_1/downloads:/downloads
            - /var/data/hydra:/config
            - /tmp:/tmp_host
        ports:
            - "5076:5076"
        labels:
            - "traefik.frontend.rule=Host:hydra.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."

networks:
    default:
        external:
            name: system_default
