version: "3"
services:
    ssl:
        image: docker.hernrup.se/letsencypt
        build: docker/letsencrypt
        command: certonly --webroot --webroot-path /var/www --agree-tos --cert-name hernrup.se --email temp@hernrup.se --renew-by-default -d test.hernrup.se --dry-run --verbose
        volumes:
            - letsencrypt:/etc/letsencrypt
            - letsencrypt_webroot:/var/www

    nginx:
        build: docker/nginx
        image: docker.hernrup.se/nginx
        restart: always
        volumes:
            - letsencrypt:/etc/letsencrypt
            - letsencrypt_webroot:/var/letsencrypt

            # - ./docker/nginx/files/etc/nginx/:/etc/nginx/
            - .data/nginx/.htpasswd:/etc/.htpasswd
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - plex
            - sonarr
            - nzb
            - potatoe
            - registry
        # links:
            # - vpn:nzb

    plex:
        image: linuxserver/plex
        restart: always
        volumes:
            - .data/plex:/config
            - ${TV_DIR}:/data/tvshows
            - ${MOVIE_DIR}:/data/movies
        # network_mode: host
        ports:
            - "32400:32400"
            - "32400:32400/udp"
            - "32469:32469"
            - "32469:32469/udp"
            - "1900:1900/udp"

    sonarr:
        image: linuxserver/sonarr
        restart: always
        volumes:
            - ".data/sonarr/etc:/config"
            - "${TV_DIR}:/tv"
            - .data/downloads:/downloads
        # depends_on:
            # - vpn
        # links:
            # - vpn:nzb

    nzb:
        image: linuxserver/sabnzbd
        restart: always
        volumes:
            - .data/downloads:/downloads
            - .data/nzb/incomplete:/incomplete-downloads
            - .data/nzb/etc:/config
        # depends_on:
            # - vpn
        # network_mode:
            # "service:vpn"

    potatoe:
        image: linuxserver/couchpotato
        restart: always
        volumes:
            - ".data/couchpotatoe/etc:/config"
            - ".data/downloads:/downloads"
            - "${MOVIE_DIR}:/movies"

    registry:
        restart: always
        image: registry:2
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/.htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
            - ".data/docker-registry:/var/lib/registry"
            - .data/letsencrypt/etc/live/hernrup.se:/certs
            - .data/registry/auth:/auth

    vpn:
        image: dperson/openvpn-client
        cap_add:
            - NET_ADMIN
        volumes:
            - .data/vpn:/vpn

    backup:
        image: docker.hernrup.se/hernrup/backup:develop
        restart: always
        build:
            context: ./docker/backupninja
        volumes:
            - .data/backupninja/.ssh:/root/.ssh
            - ./backupninja/backupninja.conf:/etc/backupninja.conf
            - ./backupninja/ssmtp.conf:/etc/ssmtp/ssmtp.conf
            - ./backupninja/backup.d:/etc/backupninja
            - /mnt/media_1:/mnt/media_1
        # depends_on:
            # - smtp
    #
    # smtp:
    #     image: namshi/smtp
    #     ports:
    #         - "25:25"
    #     environment:
    #         GMAIL_USER: ${GMAIL_USER}
    #         GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    #         MAILNAME: hernrup.se
    #         # RELAY_NETWORKS: :0.0.0.0/0
    #         # SMARTHOST_ADDRESS: ${SMTP_HOST}
    #         # SMARTHOST_USER: ${SMTP_USER}
    #         # SMARTHOST_PASSWORD: ${SMTP_PASSWORD}
    #         # SMARTHOST_PORT: ${SMTP_PORT}
    #         # SMARTHOST_ALIASES: "*.binero.se"
    #     restart: always
    #
    ha:
      image: homeassistant/home-assistant
      volumes:
        - .data/etc/homeassistant:/config
        - /etc/localtime:/etc/localtime:ro
      # devices:
      #   - /dev/ttyUSB0:/dev/ttyUSB0
      #   - /dev/ttyUSB1:/dev/ttyUSB1
      #   - /dev/ttyACM0:/dev/ttyACM0
      ports:
          - "8123:8123"
      restart: always

volumes:
    letsencrypt:
        driver: local
    letsencrypt_webroot:
        driver: local
