version: "3"
services:

    plex:
        image: linuxserver/plex
        restart: unless-stopped
        volumes:
            - .data/plex:/config
            - .data/plex_tmp:/tmp
            - ${TV_DIR}:/data/tvshows
            - ${MOVIE_DIR}:/data/movies
            - /mnt/media_1/tmp_movies:/data/tmp_movies
            - /mnt/media_1/home_movies:/data/home_movies
            - /mnt/media_1/photos:/data/photos
        environment:
            - VERSION=latest
        ports:
            - "32400:32400"
            - "32400:32400/udp"
            - "32469:32469"
            - "32469:32469/udp"
            - "1900:1900/udp"
            - "8889:8888"
        network_mode: "host"
        # networks:
            # - ov
        labels:
            - "traefik.frontend.rule=Host:plex.hernrup.se"
            - "traefik.enable=true"
            - "traefik.port=32400"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."

    sonarr:
        image: linuxserver/sonarr
        restart: unless-stopped
        volumes:
            - ".data/sonarr/etc:/config"
            - "${TV_DIR}:/tv"
            - downloads:/downloads
        ports:
            - "8001:8989"
        # depends_on:
            # - vpn
        # links:
            # - vpn:nzb
        networks:
            - ov
        labels:
            - "traefik.frontend.rule=Host:tv.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."

    nzb:
        image: linuxserver/sabnzbd
        restart: unless-stopped
        volumes:
            - downloads:/downloads
            - nzb_temp:/incomplete-downloads
            - .data/nzb/etc:/config
        ports:
            - "8002:8080"
        # depends_on:
            # - vpn
        # network_mode:
            # "service:vpn"
        networks:
            - ov
        labels:
            - "traefik.frontend.rule=Host:nzb.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."

    potatoe:
        image: linuxserver/couchpotato
        restart: unless-stopped
        volumes:
            - ".data/couchpotatoe/etc:/config"
            - downloads:/downloads
            - "${MOVIE_DIR}:/movies"
        ports:
            - "8003:5050"
        labels:
            - "traefik.frontend.rule=Host:movie.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."
    #
    # registry:
    #     restart: unless-stopped
    #     image: registry:2
    #     environment:
    #         REGISTRY_AUTH: htpasswd
    #         REGISTRY_AUTH_HTPASSWD_PATH: /auth/.htpasswd
    #         REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #     volumes:
    #         - ".data/docker-registry:/var/lib/registry"
    #         - .data/letsencrypt/etc/live/hernrup.se:/certs
    #         - .data/registry/auth:/auth
    #
    # vpn:
    #     image: dperson/openvpn-client
    #     cap_add:
    #         - NET_ADMIN
    #     volumes:
    #         - .data/vpn:/vpn

    #
    # smtp:
    #     image: namshi/smtp
    #     ports:
    #         - "25:25"
    #     environment:
    #         GMAIL_USER: ${GMAIL_USER}
    #         GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    #         MAILNAME: hernrup.se
    #         # RELAY_NETWORKS: :0.0.0.0/0
    #         # SMARTHOST_ADDRESS: ${SMTP_HOST}
    #         # SMARTHOST_USER: ${SMTP_USER}
    #         # SMARTHOST_PASSWORD: ${SMTP_PASSWORD}
    #         # SMARTHOST_PORT: ${SMTP_PORT}
    #         # SMARTHOST_ALIASES: "*.binero.se"
    #     restart: always
    #
    #

    consul:
        image: docker.hernrup.se/consul
        build: docker/consul
        ports:
            - "8500:8500"
        environment:
            - CONSUL_BIND=10.98.0.0/24
        networks:
            - ov
        labels:
            - "traefik.frontend.rule=Host:consul.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."
        volumes:
            - consul:/data


    hass:
      image: homeassistant/home-assistant
      restart: always
      volumes:
        - ./config/homeassistant:/config
        - .data/homeassistant:/data
        - .:/src
        - /etc/localtime:/etc/localtime:ro
      devices:
          - /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A128MSXO-if00-port0:/dev/serial/by-id/usb-RFXCOM_RFXtrx433_A128MSXO-if00-port0
      ports:
          - "8123:8123"
      labels:
          - "traefik.frontend.rule=Host:hass.hernrup.se"
          - "traefik.enable=true"
      networks:
          - ov

    influxdb:
        image: influxdb
        restart: unless-stopped
        ports:
            - "8086:8086"
        volumes:
            - .data/influxdb:/var/lib/influxdb
        networks:
            - ov

    chronograf:
        image: docker.hernrup.se/chronograf
        build: ./docker/chronograf
        restart: unless-stopped
        ports:
            - "8888:8888"
        volumes:
            - .data/chronograf:/var/lib/chronograf
        networks:
            - ov

    deconz:
        image: joch/deconz
        ports:
            - "8080:8080"
        volumes:
            - .data/deconz:/root/.local/share/dresden-elektronik/deCONZ
        devices:
            - /dev/ttyUSB0
        restart: unless-stopped
        privileged: true
        networks:
            - ov
    #
    # portainer:
    #     image: portainer/portainer
    #     volumes:
    #         - .data/portainer:/data
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     ports:
    #         - "9000:9000"
    #     networks:
    #         - ov
    #
    #
    mqtt:
        container_name: mqtt
        restart: unless-stopped
        image: eclipse-mosquitto
        volumes:
            - ./config/mosquitto:/mosquitto/config
            - .data/mosquitto:/mosquitto/data
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "1883:1883"
            - "9001:9001"
        networks:
            - ov


    traefik:
        image: traefik
        command: --api --docker --docker.domain=hernrup.se
        ports:
            - "80:80"
            - "443:443"
            - "8009:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config/traefik/traefik.toml:/traefik.toml
            - letsencrypt:/etc/acme
        labels:
            - "traefik.frontend.rule=Host:traefik.hernrup.se"
            - "traefik.enable=true"
            - "traefik.port=8080"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."
        networks:
            - ov

    whoami:
        image: emilevauge/whoami
        labels:
            - "traefik.frontend.rule=Host:home.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."
        networks:
            - ov

volumes:
    letsencrypt:
        driver: local
    letsencrypt_webroot:
        driver: local
    downloads:
        driver: local
    nzb_temp:
        driver: local
    consul:
        driver: local
    backup_tmp:
        driver: local

networks:
    ov:
        driver: bridge
        ipam:
            config:
                - subnet: 10.98.0.0/24
