version: "3"
services:

    hass:
        image: homeassistant/home-assistant:0.103.5
        volumes:
            - ./services/homeassistant:/config
            - /var/data/homeassistant:/data
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "8123:8123"
        labels:
            - "traefik.frontend.rule=Host:hass.hernrup.se"
            - "traefik.enable=true"
        devices:
            - /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A128MSXO-if00-port0:/dev/serial/by-id/usb-RFXCOM_RFXtrx433_A128MSXO-if00-port0
        restart: unless-stopped

    influxdb:
        image: influxdb
        volumes:
            - /var/data/influxdb:/var/lib/influxdb
        restart: unless-stopped

    chronograf:
        image: chronograf
        command: chronograf --influxdb-url=http://influxdb:8086
        volumes:
            - /var/data/chronograf:/var/lib/chronograf
        labels:
            - "traefik.frontend.rule=Host:chronograf.hernrup.se"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=admin:$$apr1$$gagmyckp$$QOlwxjImT3OO8DWi2Z.P5."
        restart: unless-stopped

    deconz:
        image: marthoc/deconz:amd64-2.05.71
        volumes:
            - /var/data/deconz:/root/.local/share/dresden-elektronik/deCONZ
        devices:
            - /dev/ttyUSB0
        privileged: true
        labels:
            - "traefik.port=8080"
        restart: unless-stopped
        environment:
            - DECONZ_WEB_PORT=8080

    mqtt:
        image: eclipse-mosquitto
        volumes:
            - ./services/mqtt:/mosquitto/config
            - /var/data/mqtt:/mosquitto/data
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "1883:1883"
            - "9001:9001"
        restart: unless-stopped

networks:
    default:
        external:
            name: system_default
