- alias: is-home
  trigger:
      - platform: state
        entity_id: switch.Home
        from: 'off'
        to: 'on'
  action:
      - service: light.turn_on
        entity_id: light.play_area_downstairs

      - service: switch.turn_on
        entity_id: switch.living_room_power

- alias: is-away
  trigger:
      - platform: state
        entity_id: switch.home
        from: 'on'
        to: 'off'
  action:
      - service: light.turn_off
        entity_id: light.play_area_downstairs

      - service: switch.turn_off
        entity_id: switch.living_room_power


- alias: Use remote to set is home
  trigger:
      - platform: event
        event_type: button_pressed
        event_data: {"state": "on", "entity_id": "switch.home_remote"}
  action:
        service: switch.turn_on
        entity_id: switch.home

- alias: Use remote to set is away
  trigger:
      - platform: event
        event_type: button_pressed
        event_data: {"state": "off", "entity_id": "switch.home_remote"}
  action:
        service: switch.turn_off
        entity_id: switch.home

- alias: mickes phone is home, trigger home
  trigger:
      platform: state
      entity_id: device_tracker.theawesomephone
      from: 'not_home'
      to: 'home'
  action:
      - service: switch.turn_on
        entity_id: switch.home
      - service: notify.notify
        data:
            title: 'Micke is home'
            message: 'Home mode set'

 



