toggles:
    name: Modes
    icon: mdi:home
    entities:
        - switch.home
        - script.reload
        - script.restart

temperature:
    name: Environment
    icon: mdi:home
    entities:
        - sensor.weather_temperature
        - sensor.carport_temperature
        - sensor.washing_room_temperature
        - sensor.living_room_temperature
        - sensor.bed_room_temperature
        - sensor.child_room_temperature

weather:
    name: Weather
    # icon: mdi:home
    entities:
        - sun.sun
        - sensor.weather_symbol
        - sensor.weather_temperature
        - sensor.weather_humidity
        - sensor.weather_wind_speed
        - sensor.weather_precipitation

users:
    name: Users
    # icon: mdi:home
    entities:
        - device_tracker.theawesomephone

alarm:
    name: Alarm
    icon: mdi:alert
    entities:
        - alarm_control_panel.sadebacksgatan_alarm
        - binary_sensor.carport_1
        - binary_sensor.carport_2
        - binary_sensor.entry

default_view:
    name: Home
    view: yes
    entities:
        - group.toggles
        - group.users
        - group.temperature
        - group.alarm
        - group.weather

automation_view:
    name: Automation
    view: yes
    entities:
        - group.all_automations
        - group.all_scripts

all_view:
    name: All
    view: yes
    entities:
        - group.all_automations
        - group.all_scripts
        - group.all_devices
        - group.all_switches
        - group.all_lights

