version: "3"
services:
    letsencrypt:
        image: letsencypt
        build: ../letsencrypt
        command: certonly --webroot --webroot-path /var/www --agree-tos --cert-name hernrup.se --email temp@hernrup.se --renew-by-default -d test.hernrup.se --dry-run --verbose
        volumes:
            - letsencrypt:/etc/letsencrypt
            - letsencrypt_webroot:/var/www

    nginx:
        build: .
        image: nginx
        restart: always
        volumes:
            - letsencrypt:/etc/letsencrypt
            - letsencrypt_webroot:/var/letsencrypt

            - ./files/etc/nginx:/etc/nginx
            - ./files/etc/consul_template:/etc/consul_template
            - ./files/bin/start.sh:/bin/start.sh
        ports:
            - "80:80"
            - "443:443"

volumes:
    letsencrypt:
        driver: local
    letsencrypt_webroot:
        driver: local
