version: '3.2'

services:
  consul:
    image: docker.lundalogik.com/lundalogik/crm/consul:latest
    ports:
        - 8500:8500
    environment:
      - CONSUL=consul
      - CONSUL_BIND=10.80.0.0/24
      - DATACENTER=staging
    deploy:
      replicas: 3
    networks:
      - ov

networks:
    ov:
        driver: overlay
        ipam:
            config:
                - subnet: 10.80.0.0/24
