version: '3.2'

services:

  # Service definition for Consul cluster with a minimum of 3 nodes.
  # For local development we use Compose v2 so that we have an automatically
  # created user-defined network and internal DNS for the name "consul".
  # Nodes will use Docker DNS for the service (passed in via the CONSUL
  # env var) to find each other and bootstrap the cluster.
  consul:
    image: docker.lundalogik.com/lundalogik/crm/consul:latest
    ports:
        - 8500:8500
    environment:
      - CONSUL=consul
      - CONSUL_BIND=10.80.0.0/24
      - DEVMODE=True
      - BACKUP_BUCKET=lime-staging-sql-backups
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=eu-west-1
      - DATACENTER=staging
    volumes:
      - dbbackup:/var/lime/backup_files
    networks:
      - ov_bridge
  # consul2:
  #   image: consul_test:latest
  #   environment:
  #     - CONSUL=consul
  #   command: >
  #     /usr/local/bin/containerpilot
  #   networks:
  #     - ov
  # consul3:
  #   image: consul_test:latest
  #   environment:
  #     - CONSUL=consul
  #   command: >
  #     /usr/local/bin/containerpilot
  #   networks:
  #     - ov

networks:
    ov_bridge:
        driver: bridge
        ipam:
            config:
                - subnet: 10.80.0.0/24
volumes:
    dbbackup:
        driver: local
