homeassistant:
  name: Home
  latitude: 55.8489037
  longitude: 13.6673265
  elevation: 0
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_password
    - type: homeassistant
  external_url: https://hass.hernrup.se

default_config:

lovelace:
  # mode: yaml

frontend:
  themes: !include_dir_merge_named themes

config:

mqtt:
    broker: mqtt

discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 30

# View all events in a logbook
logbook:

# Track the sun
sun:

logger:
    default: warn
    logs:
        homeassistant.components.device_tracker: info
        pydeconz: info
        homeassistant.components.deconz: info

deconz:
      host: deconz
      api_key: !secret deconz_api_key

sensor: !include sensor.yaml
switch: !include switch.yaml

weather:
  - platform: darksky
    name: darksky
    api_key: !secret darksky

influxdb:
  host: influxdb
  database: home
  ssl: false
  verify_ssl: false
  max_retries: 3
  default_measurement: state
  tags:
      source: hass
  include:
      entities:
        - sensor.weather_temperature
        - sensor.carport_temperature
        - sensor.washing_room_temperature
        - sensor.living_room_temperature
        - sensor.bed_room_temperature
        - sensor.child_room_temperature
        - sensor.weather_humidity
        - sensor.weather_wind_speed


verisure:
    username: !secret verisure_username
    password: !secret verisure_password

rfxtrx:
    device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A128MSXO-if00-port0
    debug: False
    automatic_add: true
    devices:
      # Linus sky lights | 1-2
      0b1100140180470a02010f70:
          fire_event: True
      # Windows 1 | 2-2
      0b11002b0180470a06010f70:
          fire_event: True
      # Windows 2 | 2-3
      0b1100390180470a07010f70:
          fire_event: True
      # Entryway | 1-1
      0b1100130180470a01010f70:
          fire_event: True
      # Tv | 3-1
      0b11003d0180470a09010f60:
          fire_event: True
      # Carport
      0a520d00c801006b280169:
        fire_event: True
      # Generated ARC switch
      0b11000673bc0cfe00010f70:
        fire_event: True
      # Genreated ARC light
      0b11000670bc0cfe05020f70:
        fire_event: True
      # Generated lightwave
      0a14000606bc0cf6100f70:
        fire_event: True
      "0710010041010001":
        fire_event: True


# google_assistant:
#   project_id: homeassistant-217419
#   service_account: !include SERVICE_ACCOUNT.json
#   report_state: true
#   expose_by_default: True
#   exposed_domains:
#       - switch
#       - light
#       - group
#       - scene
#       - input_boolean

notify:
    - name: notify
      platform: html5
      vapid_pub_key: !secret vapid_pub_key
      vapid_prv_key: !secret vapid_prv_key
      vapid_email: !secret vapid_email