homeassistant:
  name: Home
  latitude: 59.0831
  longitude: 12.9331
  elevation: 0
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_password

lovelace:
  mode: yaml

frontend:

config:

http:
  base_url: hass.hernrup.se

mqtt:
    broker: mqtt

discovery:
    ignore:
        - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 30

# View all events in a logbook
logbook:

# Track the sun
sun:

logger:
    default: warn
    logs:
        homeassistant.components.device_tracker: info
        pydeconz: debug
        homeassistant.components.deconz: debug

deconz:
      host: deconz
      api_key: !secret deconz_api_key

sensor: !include sensor.yaml
switch: !include switch.yaml
light: !include lights.yaml
scene: !include scene.yaml

influxdb:
  host: influxdb
  database: home
  ssl: false
  verify_ssl: false
  max_retries: 3
  default_measurement: state
  tags:
      source: hass
  include:
      entities:
        - sensor.weather_temperature
        - sensor.carport_temperature
        - sensor.washing_room_temperature
        - sensor.living_room_temperature
        - sensor.bed_room_temperature
        - sensor.child_room_temperature
        - sensor.weather_humidity
        - sensor.weather_wind_speed


verisure:
    username: !secret verisure_username
    password: !secret verisure_password

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

rfxtrx:
    device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A128MSXO-if00-port0
    debug: True

google_assistant:
    project_id: HomeAssistant
    api_key: !secret google_assistant
    expose_by_default: True
    exposed_domains:
        - switch
        - light
        - group
        - scene

notify:
    - name: notify
      platform: html5
      vapid_pub_key: !secret vapid_pub_key
      vapid_prv_key: !secret vapid_prv_key
      vapid_email: !secret vapid_email
#
# device_tracker:
#     - platform: asuswrt
#       host: 192.168.1.1
#       exclude:
#           - 192.168.1.4
#       username: !secret router_username
#       password: !secret router_password
#       interval_seconds: 15
#       consider_home: 180
#       new_device_defaults:
#           track_new_devices: True
#           hide_if_away: True
#
